2025-05-12 20:50:33,605 : INFO : root : Loading config.
2025-05-12 20:50:33,607 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2025-05-12 20:50:33,607 : WARNING : ConfigProcessor : Config file in cache changed: /Users/michaelcarman/Documents/work/mpf/happy-pinball/config/config.yaml
2025-05-12 20:50:33,607 : INFO : ConfigProcessor : Loading config from file /Users/michaelcarman/Documents/work/mpf/mpf/lib/python3.13/site-packages/mpf/mpfconfig.yaml.
2025-05-12 20:50:33,622 : INFO : ConfigProcessor : Loading config: /Users/michaelcarman/Documents/work/mpf/mpf/lib/python3.13/site-packages/mpf/mpfconfig.yaml
2025-05-12 20:50:33,622 : INFO : ConfigProcessor : Loading config from file /Users/michaelcarman/Documents/work/mpf/happy-pinball/config/config.yaml.
2025-05-12 20:50:33,623 : INFO : ConfigProcessor : Loading config: /Users/michaelcarman/Documents/work/mpf/happy-pinball/config/config.yaml
2025-05-12 20:50:33,623 : INFO : ConfigProcessor : Loading config: /Users/michaelcarman/Documents/work/mpf/happy-pinball/config/config_ball_devices.yaml
2025-05-12 20:50:33,624 : INFO : ConfigProcessor : Loading config: /Users/michaelcarman/Documents/work/mpf/happy-pinball/config/config_coils.yaml
2025-05-12 20:50:33,625 : INFO : ConfigProcessor : Loading config: /Users/michaelcarman/Documents/work/mpf/happy-pinball/config/config_switches.yaml
2025-05-12 20:50:33,626 : INFO : ConfigProcessor : Config file cache created: /var/folders/hz/r3dl9ms51016zpvrwk611s6m0000gs/T/5d6a457603c6b060ca35237bebf088e1.mpf_cache
2025-05-12 20:50:33,665 : INFO : ConfigProcessor : Loading config from cache: /var/folders/hz/r3dl9ms51016zpvrwk611s6m0000gs/T/6f665ac125edf3618cba9e13a753822f.mpf_cache
2025-05-12 20:50:33,665 : INFO : ConfigProcessor : Loading config from cache: /var/folders/hz/r3dl9ms51016zpvrwk611s6m0000gs/T/87d438dd69d0ef01003c5249e41b5d50.mpf_cache
2025-05-12 20:50:33,665 : INFO : ConfigProcessor : Loading config from cache: /var/folders/hz/r3dl9ms51016zpvrwk611s6m0000gs/T/6f665ac125edf3618cba9e13a753822f.mpf_cache
2025-05-12 20:50:33,666 : WARNING : ConfigProcessor : Config file in cache changed: /Users/michaelcarman/Documents/work/mpf/happy-pinball/modes/base/config/base.yaml
2025-05-12 20:50:33,666 : INFO : ConfigProcessor : Loading config from file /Users/michaelcarman/Documents/work/mpf/happy-pinball/modes/base/config/base.yaml.
2025-05-12 20:50:33,666 : INFO : ConfigProcessor : Loading config: /Users/michaelcarman/Documents/work/mpf/happy-pinball/modes/base/config/base.yaml
2025-05-12 20:50:33,667 : INFO : ConfigProcessor : Config file cache created: /var/folders/hz/r3dl9ms51016zpvrwk611s6m0000gs/T/d9ff39e0ccd80af39f7d36bb6b40dd93.mpf_cache
2025-05-12 20:50:33,667 : INFO : ConfigProcessor : Loading config from file /Users/michaelcarman/Documents/work/mpf/happy-pinball/modes/bumpers/config/bumpers.yaml.
2025-05-12 20:50:33,668 : INFO : ConfigProcessor : Loading config: /Users/michaelcarman/Documents/work/mpf/happy-pinball/modes/bumpers/config/bumpers.yaml
2025-05-12 20:50:33,669 : INFO : ConfigProcessor : Config file cache created: /var/folders/hz/r3dl9ms51016zpvrwk611s6m0000gs/T/ac07971a64f12a0788c85bcc38792825.mpf_cache
2025-05-12 20:50:33,670 : INFO : Machine : Mission Pinball Framework Core Engine v0.80.0.dev7
2025-05-12 20:50:33,670 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': True, 'configfile': ['config.yaml'], 'force_assets_load': False, 'platform_integration_test': False, 'jsonlogging': False, 'logfile': 'logs/2025-05-12-20-50-33-mpf-LPCVQLKF70.log', 'pause': False, 'production': False, 'text_ui': False, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': 'virtual', 'syslog_address': None, 'full_logfile_path': '/Users/michaelcarman/Documents/work/mpf/happy-pinball/logs/2025-05-12-20-50-33-mpf-LPCVQLKF70.log'}
2025-05-12 20:50:33,670 : INFO : Machine : MPF path: /Users/michaelcarman/Documents/work/mpf/mpf/lib/python3.13/site-packages/mpf
2025-05-12 20:50:33,670 : INFO : Machine : Machine path: /Users/michaelcarman/Documents/work/mpf/happy-pinball
2025-05-12 20:50:33,670 : INFO : Machine : Platform: darwin
2025-05-12 20:50:33,670 : INFO : Machine : Python executable location: /Users/michaelcarman/Documents/work/mpf/mpf/bin/python3.13
2025-05-12 20:50:33,670 : INFO : Machine : Python version: 3.13.3 (64-bit)
2025-05-12 20:50:33,670 : INFO : Machine : Initializing MPF...
2025-05-12 20:50:33,701 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2025-05-12 20:50:33,708 : INFO : EventManager : Event: ======'machine_var_player1_score'====== Args={'value': 8675309, 'prev_value': None, 'change': True}
2025-05-12 20:50:33,708 : INFO : EventManager : Event: ======'machine_var_player2_score'====== Args={'value': 4321523, 'prev_value': None, 'change': True}
2025-05-12 20:50:33,708 : INFO : EventManager : Event: ======'machine_var_master_volume'====== Args={'value': 0.5, 'prev_value': None, 'change': True}
2025-05-12 20:50:33,708 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'Mission Pinball Framework v0.80.0.dev7', 'prev_value': None, 'change': True}
2025-05-12 20:50:33,708 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'Mission Pinball Framework v0.80.0.dev7, Config version:6, Show version: 6, BCP version:1.1', 'prev_value': None, 'change': True}
2025-05-12 20:50:33,709 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.13.3', 'prev_value': None, 'change': True}
2025-05-12 20:50:33,719 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'macOS-15.3.1-arm64-arm-64bit-Mach-O', 'prev_value': None, 'change': True}
2025-05-12 20:50:33,719 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Darwin', 'prev_value': None, 'change': True}
2025-05-12 20:50:33,719 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '24.3.0', 'prev_value': None, 'change': True}
2025-05-12 20:50:33,719 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': 'Darwin Kernel Version 24.3.0: Thu Jan  2 20:24:22 PST 2025; root:xnu-11215.81.4~3/RELEASE_ARM64_T6041', 'prev_value': None, 'change': True}
2025-05-12 20:50:33,719 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'arm64', 'prev_value': None, 'change': True}
2025-05-12 20:50:33,719 : INFO : EventManager : Event: ======'machine_var_log_file_path'====== Args={'value': '/Users/michaelcarman/Documents/work/mpf/happy-pinball/logs/2025-05-12-20-50-33-mpf-LPCVQLKF70.log', 'prev_value': None, 'change': True}
2025-05-12 20:50:33,719 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2025-05-12 20:50:33,725 : ERROR : asyncio : Exception in callback EventManager._async_handler_done()() at /Users/michaelcarman/Documents/work/mpf/mpf/lib/python3.13/site-packages/mpf/core/events.py:124
handle: <Handle EventManager._async_handler_done()() at /Users/michaelcarman/Documents/work/mpf/mpf/lib/python3.13/site-packages/mpf/core/events.py:124>
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.13/3.13.3/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michaelcarman/Documents/work/mpf/mpf/lib/python3.13/site-packages/mpf/core/events.py", line 127, in _async_handler_done
    future.result()
    ~~~~~~~~~~~~~^^
  File "/Users/michaelcarman/Documents/work/mpf/mpf/lib/python3.13/site-packages/mpf/core/device_manager.py", line 89, in _load_device_modules
    await self.machine.mode_controller.load_mode_devices()
  File "/Users/michaelcarman/Documents/work/mpf/mpf/lib/python3.13/site-packages/mpf/core/mode_controller.py", line 86, in load_mode_devices
    await mode.load_mode_devices()
  File "/Users/michaelcarman/Documents/work/mpf/mpf/lib/python3.13/site-packages/mpf/core/mode.py", line 438, in load_mode_devices
    settings = device.validate_and_parse_config(settings, True, "mode:" + self.name)
  File "/Users/michaelcarman/Documents/work/mpf/mpf/lib/python3.13/site-packages/mpf/devices/shot.py", line 79, in validate_and_parse_config
    config = super().validate_and_parse_config(config, is_mode_config, debug_prefix)
  File "/Users/michaelcarman/Documents/work/mpf/mpf/lib/python3.13/site-packages/mpf/core/device.py", line 108, in validate_and_parse_config
    self.machine.config_validator.validate_config(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self.config_section, config, self.name, "device", prefix=debug_prefix)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michaelcarman/Documents/work/mpf/mpf/lib/python3.13/site-packages/mpf/core/config_validator.py", line 164, in validate_config
    return self._validate_config(config_spec, source, base_spec=base_spec, add_missing_keys=add_missing_keys,
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                 validation_failure_info=validation_failure_info)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michaelcarman/Documents/work/mpf/mpf/lib/python3.13/site-packages/mpf/core/config_validator.py", line 204, in _validate_config
    processed_config[k] = self.validate_config_item(
                          ~~~~~~~~~~~~~~~~~~~~~~~~~^
        this_spec[k], item=source[k],
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        validation_failure_info=ValidationPath(validation_failure_info, k))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michaelcarman/Documents/work/mpf/mpf/lib/python3.13/site-packages/mpf/core/config_validator.py", line 256, in validate_config_item
    new_list.append(self.validate_item(i, validation, validation_failure_info))
                    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michaelcarman/Documents/work/mpf/mpf/lib/python3.13/site-packages/mpf/core/config_validator.py", line 699, in validate_item
    return self.validator_list[validator](item, validation_failure_info=validation_failure_info, param=param)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michaelcarman/Documents/work/mpf/mpf/lib/python3.13/site-packages/mpf/core/config_validator.py", line 413, in _validate_type_machine
    raise self.validation_error(item, validation_failure_info,
                                'Device "{}" not found in "{}:" section in your config.'.format(item, param),
                                6)
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ConfigValidator: Config validation error: Entry mode:bumpers:shots:bumper_right:switch = "s_bumper_rights" is not valid. Device "s_bumper_rights" not found in "switches:" section in your config. Error Code: CFE-ConfigValidator-6 (https://missionpinball.org/logs)
2025-05-12 20:50:33,729 : INFO : Machine : Starting the main run loop with active modes: []
2025-05-12 20:50:33,729 : WARNING : Machine : Attract mode is not active, game will not be playable. Please check your attract mode configuration.
2025-05-12 20:50:33,729 : INFO : Machine : Shutting down...
2025-05-12 20:50:33,729 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2025-05-12 20:50:34,732 : ERROR : Machine : Runtime Exception
Traceback (most recent call last):
  File "/Users/michaelcarman/Documents/work/mpf/mpf/lib/python3.13/site-packages/mpf/core/machine.py", line 808, in _run_loop
    raise self._exception['exception']
  File "/opt/homebrew/Cellar/python@3.13/3.13.3/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michaelcarman/Documents/work/mpf/mpf/lib/python3.13/site-packages/mpf/core/events.py", line 127, in _async_handler_done
    future.result()
    ~~~~~~~~~~~~~^^
  File "/Users/michaelcarman/Documents/work/mpf/mpf/lib/python3.13/site-packages/mpf/core/device_manager.py", line 89, in _load_device_modules
    await self.machine.mode_controller.load_mode_devices()
  File "/Users/michaelcarman/Documents/work/mpf/mpf/lib/python3.13/site-packages/mpf/core/mode_controller.py", line 86, in load_mode_devices
    await mode.load_mode_devices()
  File "/Users/michaelcarman/Documents/work/mpf/mpf/lib/python3.13/site-packages/mpf/core/mode.py", line 438, in load_mode_devices
    settings = device.validate_and_parse_config(settings, True, "mode:" + self.name)
  File "/Users/michaelcarman/Documents/work/mpf/mpf/lib/python3.13/site-packages/mpf/devices/shot.py", line 79, in validate_and_parse_config
    config = super().validate_and_parse_config(config, is_mode_config, debug_prefix)
  File "/Users/michaelcarman/Documents/work/mpf/mpf/lib/python3.13/site-packages/mpf/core/device.py", line 108, in validate_and_parse_config
    self.machine.config_validator.validate_config(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self.config_section, config, self.name, "device", prefix=debug_prefix)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michaelcarman/Documents/work/mpf/mpf/lib/python3.13/site-packages/mpf/core/config_validator.py", line 164, in validate_config
    return self._validate_config(config_spec, source, base_spec=base_spec, add_missing_keys=add_missing_keys,
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                 validation_failure_info=validation_failure_info)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michaelcarman/Documents/work/mpf/mpf/lib/python3.13/site-packages/mpf/core/config_validator.py", line 204, in _validate_config
    processed_config[k] = self.validate_config_item(
                          ~~~~~~~~~~~~~~~~~~~~~~~~~^
        this_spec[k], item=source[k],
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        validation_failure_info=ValidationPath(validation_failure_info, k))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michaelcarman/Documents/work/mpf/mpf/lib/python3.13/site-packages/mpf/core/config_validator.py", line 256, in validate_config_item
    new_list.append(self.validate_item(i, validation, validation_failure_info))
                    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michaelcarman/Documents/work/mpf/mpf/lib/python3.13/site-packages/mpf/core/config_validator.py", line 699, in validate_item
    return self.validator_list[validator](item, validation_failure_info=validation_failure_info, param=param)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michaelcarman/Documents/work/mpf/mpf/lib/python3.13/site-packages/mpf/core/config_validator.py", line 413, in _validate_type_machine
    raise self.validation_error(item, validation_failure_info,
                                'Device "{}" not found in "{}:" section in your config.'.format(item, param),
                                6)
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ConfigValidator: Config validation error: Entry mode:bumpers:shots:bumper_right:switch = "s_bumper_rights" is not valid. Device "s_bumper_rights" not found in "switches:" section in your config. Error Code: CFE-ConfigValidator-6 (https://missionpinball.org/logs)
2025-05-12 20:50:34,739 : INFO : root : MPF run loop ended.
